### ISSUE TITLE
Query not returned

### ISSUE THREAD

**Issue by Ethan-Hill** [morhogg/use-client-router#1]
The route query is not being returned at all

```js
  const router = useClientRouter();
  const nrouter = useRouter();

  console.log(nrouter.query);
  console.log(router.query);
```
![firefox_bC1xACplB9](https://user-images.githubusercontent.com/45304268/104835287-85a19100-589d-11eb-9e90-12be99f85b61.png)

The next router returns the query after its ready, the client router doesn't return it at all.

**Comment by hexetia** [comment]
I can't reproduce the problem, can you provide a repository with some code that I can use to test your case?

I used this code:

```
├── pages
│   ├── post/[pid].js
```
`http://localhost:3000/post/abc`
```jsx
import { useClientRouter } from "use-client-router";
import { useRouter } from 'next/router'

const Post = () => {
    const router = useClientRouter();
    const nrouter = useRouter();

    console.log('NextRouter.query', nrouter.query);
    console.log('useClientRouter.query', router.query);

    return <p>Post: {router.query.pid}</p>
}

export default Post
```

![Screenshot_20210117_145301](https://user-images.githubusercontent.com/4311885/104851444-ca481f00-58d3-11eb-94a8-c19337b20f7c.png)

**Comment by hexetia** [comment]
If you have more details on how to reproduce the issue open it again

**Comment by miracle2k** [comment]
They are probably talking about the actual query string, i.e. `/browe?log=1` - `log` is not included.
